"""
Django settings for newsportal project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0c0jwk%%03+fj!rj*b#-sc9n$9)+*2yps5(7rii^#4e!%&nf3$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',
    'django.contrib.flatpages',
    'fpages',
    'news',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.yandex',
    'django_apscheduler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',

    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',

]

ROOT_URLCONF = 'newsportal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'newsportal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/news/'

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = "example@yandex.ru"
EMAIL_HOST_PASSWORD = "iliezvcovrxqizez"
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

DEFAULT_FROM_EMAIL = "example@yandex.ru"

# use this for signals
SITE_URL = "http://127.0.0.1:8000"

CELERY_BROKER_URL = 'redis://192.168.1.15:6379'
CELERY_RESULT_BACKEND = 'redis://192.168.1.15:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CACHES = {
    'default': {
        'TIMEOUT': 60, # добавляем стандартное время ожидания в минуту (по умолчанию это 5 минут — 300 секунд)
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache_files'), # Указываем, куда будем сохранять кэшируемые файлы! Не забываем создать папку cache_files внутри папки с manage.py!
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'style': '{',
    'formatters': {
        'debug-formatter': {
            'format': '{asctime} {levelname} {message}',
            'style': '{',
        },
        'info-formatter': {
            'format': '{asctime} {levelname} {module} {message}',
            'style': '{',
        },
        'warn-formatter': {
            'format': '{asctime} {levelname} {pathname} {message}',
            'style': '{',
        },
        'error-formatter': {
            'format': '{asctime} {levelname} {pathname} {message} {exc_info}',
            'style': '{',
        },
    },
    'filters': {
        'debug': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'no_debug': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'error_level': {
            '()': 'news.logging.LogLevels',
            'levels': ['ERROR', 'CRITICAL'],
        },
        'warning_level': {
            '()': 'news.logging.LogLevels',
            'levels': ['WARNING'],
        },
        'debug_level': {
            '()': 'news.logging.LogLevels',
            'levels': ['DEBUG', 'INFO'],
        },
    },
    'handlers': {
        'console_debug': {
            'filters': ['debug', 'debug_level'],
            'formatter': 'debug-formatter',
            'class': 'logging.StreamHandler',
        },
        'console_warning': {
            'level': 'WARNING',
            'filters': ['debug', 'warning_level'],
            'formatter': 'warn-formatter',
            'class': 'logging.StreamHandler',
        },
        'console_error': {
            'level': 'ERROR',
            'filters': ['debug', 'error_level'],
            'formatter': 'error-formatter',
            'class': 'logging.StreamHandler',
        },
        'file_info': {
            'level': 'INFO',
            'filters': ['no_debug'],
            'formatter': 'info-formatter',
            'class': 'logging.FileHandler',
            'filename': 'general.log',
        },
        'file_error': {
            'level': 'ERROR',
            'formatter': 'error-formatter',
            'class': 'logging.FileHandler',
            'filename': 'errors.log',
        },
        'file_security': {
            'formatter': 'info-formatter',
            'class': 'logging.FileHandler',
            'filename': 'security.log',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['no_debug'],
            'formatter': 'warn-formatter',
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'django': {
            # 'level': DEBUG,
            'handlers': [
                'console_debug',
                'console_warning',
                'console_error',
                'file_info',
            ],
            'propagate': True,
        },
        'django.request': {
            'level': 'ERROR',
            'handlers': [
                'file_error',
                'mail_admins'
            ],
        },
        'django.server': {
            'level': 'ERROR',
            'handlers': [
                'file_error',
                'mail_admins'
            ],
        },
        'django.template': {
            'level': 'ERROR',
            'handlers': ['file_error'],
        },
        'django.db.backends': {
            'level': 'ERROR',
            'handlers': ['file_error'],
        },
        'django.security': {
            'level': 'DEBUG',
            'handlers': ['file_security'],
        },
    }
}